# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsHeaven < Formula
  desc "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
  homepage "https://github.com/kcaebe/dns-heaven"
  version "0.1.8"

  depends_on "go"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.8/dns-heaven_0.1.8_darwin_arm64.tar.gz"
      sha256 "479dbc68cef47996e7c19141672b0b845114616f484ca9e661ba6f05920934f7"

      def install
        bin.install "dns-heaven"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.8/dns-heaven_0.1.8_darwin_amd64.tar.gz"
      sha256 "2adc6e531e344441a2dd0a71e5f323a78ccc5be25b89e9a84a2cf45db2c269a1"

      def install
        bin.install "dns-heaven"
      end
    end
  end

  service do
    run [#{bin}/dns-heaven]
    keep_alive true
    requires_root true
  end

  test do
    system "#{bin}/dns-heaven -version"
  end
end
