# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsHeaven < Formula
  desc "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
  homepage "https://github.com/kcaebe/dns-heaven"
  version "0.2.0"

  depends_on "go"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.2.0/dns-heaven_0.2.0_darwin_arm64.tar.gz"
      sha256 "34377621a6694b2c6fc52c372d48d461a8232228debcf1c80c74c43a2f863b4e"

      def install
        bin.install "dns-heaven"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.2.0/dns-heaven_0.2.0_darwin_amd64.tar.gz"
      sha256 "9593259decf92e864823eaaa1e2325f0f1eb3f5cdfc5173d49decf0b066221ae"

      def install
        bin.install "dns-heaven"
      end
    end
  end

  service do
    run bin/"dns-heaven"
    keep_alive true
    require_root true
  end

  test do
    system 'bin/"dns-heaven" -version'
  end
end
